package com.github.pokee.pswf.connection.handler;

import com.github.pokee.pswf.exception.NoHandlerForRouteException;
import com.github.pokee.pswf.exception.request.NoContentException;
import com.github.pokee.pswf.request.Request;
import com.github.pokee.pswf.response.Response;
import com.github.pokee.pswf.response.writers.ResponseWriter;
import com.github.pokee.pswf.router.Context;
import com.github.pokee.pswf.router.ErrorHandler;
import com.github.pokee.pswf.router.Router;
import com.github.pokee.pswf.router.handler.Handler;

import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.List;

/**
 * Handles client requests by routing them through a defined router and managing response generation.
 * This handler is responsible for the entire lifecycle of the HTTP request, from reading to response writing.
 */
public class BasicRouterClientHandler implements ClientHandler {

    private final ErrorHandler errorHandler;  // Handles errors during request processing.
    private final Router router;  // Routes incoming requests to appropriate handlers.

    /**
     * Constructs a BasicRouterClientHandler with a specified router and error handler.
     *
     * @param router       The router to use for determining the route for each request.
     * @param errorHandler The handler used for processing exceptions that occur during request handling.
     */
    public BasicRouterClientHandler(final Router router, final ErrorHandler errorHandler) {
        this.router = router;
        this.errorHandler = errorHandler;
    }

    /**
     * Processes a given context to generate a response by executing all applicable handlers.
     * Throws exceptions if no handlers are available or if no response is generated.
     *
     * @param context The context containing the request and the space to set the response.
     * @return The response generated by handling the request.
     * @throws NoContentException If no response is generated after processing.
     */
    private Response getResponseForContext(final Context context) throws NoContentException {
        final List<Handler> handlers = context.getHandlers();
        if (handlers.isEmpty()) {
            throw new NoHandlerForRouteException();
        }
        for (final Handler handler : handlers) {
            handler.handle(context);
        }
        final Response response = context.getResponse();
        if (response == null) {
            throw new NoContentException();
        }
        return response;
    }

    @Override
    public void handle(final Socket socket) throws IOException {
        try (socket;
             final BufferedReader reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
             final BufferedOutputStream writer = new BufferedOutputStream(socket.getOutputStream())) {

            final Request request = Request.readRequest(reader);
            System.out.println(request.prettyPrint());

            final ResponseWriter responseWriter = request.version().getWriter();
            if (responseWriter == null) {
                throw new UnsupportedOperationException("Unsupported version for writing: " + request.version());
            }

            Response response;
            try {
                final Context context = this.router.createContext(request);
                response = this.getResponseForContext(context);
            } catch (final Throwable throwable) {
                response = this.errorHandler.handle(request, throwable);
            }

            responseWriter.write(response, writer);
            writer.flush();
        } finally {
            System.out.println("Bye " + socket.getInetAddress());
        }
    }

}
